/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentvideopj;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import rentvideopj.DBAccess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class RentVideo extends javax.swing.JFrame {
    int checkTransaction=0;
    int Total=0;
    LocalDate currentDate = LocalDate.now();          
    
    
    /**
     * Creates new form RentVideo
     */
    public RentVideo() {
        initComponents();
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateDateTime();
            }
        });
        timer.start();
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPriceRent1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNameVid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtNameCus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdCus = new javax.swing.JTextField();
        txtIdVid = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JLabel();
        txtPriceRent = new javax.swing.JLabel();
        txtAu = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtPriceRent2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtPriceRent3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtPriceRent4 = new javax.swing.JLabel();
        txtPriceRent5 = new javax.swing.JLabel();
        txtPriceRent6 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JLabel();
        txtCusPay = new javax.swing.JTextField();
        txtExchange = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtActive = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAddr = new javax.swing.JTextField();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        txtPriceRent7 = new javax.swing.JLabel();
        selectDay = new com.toedter.calendar.JDateChooser();

        txtPriceRent1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPriceRent1.setText("PriceOfDay");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Rent Video");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");

        txtNameVid.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("DOB");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Phone");

        txtDOB.setEditable(false);

        txtPhone.setEditable(false);

        txtNameCus.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Status Rent");

        txtStatus.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name video", "Amount", "Number of Rental Day", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(3).setMinWidth(2);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Video");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Customer");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("ID");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Name");

        txtIdCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCusActionPerformed(evt);
            }
        });
        txtIdCus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdCusKeyReleased(evt);
            }
        });

        txtIdVid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdVidKeyReleased(evt);
            }
        });

        txtType.setEditable(false);

        txtPrice.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Type");

        txtAuthor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAuthor.setText("Author");

        txtPriceRent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPriceRent.setText("PriceOfDay");

        txtAu.setEditable(false);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtPriceRent2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPriceRent2.setText("Quantity");

        txtPriceRent3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPriceRent3.setText("Amount in Store");

        txtAmount.setEditable(false);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtPriceRent4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPriceRent4.setText("Total:");

        txtPriceRent5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPriceRent5.setText("Money customer pay: ");

        txtPriceRent6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPriceRent6.setText("Exchange:");

        txtTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalPrice.setText("0");

        txtCusPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCusPayKeyReleased(evt);
            }
        });

        txtExchange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtExchange.setText("0");
        txtExchange.setToolTipText("");

        btnPay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Address");

        txtActive.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Active");

        txtAddr.setEditable(false);

        labelDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDate.setText(".");
        labelDate.setToolTipText("");

        labelTime.setText(".");

        txtPriceRent7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPriceRent7.setText("Date Of Return");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtActive, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(txtPriceRent2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205)
                                .addComponent(txtPriceRent7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(76, 76, 76)
                                                .addComponent(txtIdCus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(txtNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPriceRent, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addComponent(txtPriceRent3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdVid, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtNameVid, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtType, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtAu, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(selectDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPriceRent6)
                                    .addComponent(txtPriceRent4)
                                    .addComponent(txtPriceRent5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCusPay, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(0, 475, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelDate)
                            .addComponent(labelTime))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(txtIdCus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPriceRent4)
                            .addComponent(txtTotalPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(24, 24, 24)
                                .addComponent(txtAuthor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPriceRent))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdVid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtNameVid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtAu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtActive, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCusPay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtExchange))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPriceRent5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPriceRent6)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPay)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAdd)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPriceRent3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPriceRent2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPriceRent7)
                                .addComponent(selectDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        int cuspay= Integer.parseInt(txtCusPay.getText());
        int total= Integer.parseInt(txtTotalPrice.getText());

        if(cuspay >= total){
            checkTransaction=0;
        
        DBAccess a= new DBAccess();
        int maxIDRent=0;
        ResultSet rs = a.Query("SELECT MAX(IDRent)AS maxid FROM RentalTransaction");
        Date selectedDate = selectDay.getDate();
        LocalDate selectedLocalDate = selectedDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();     
                try {
                    if(rs.next()){
                        maxIDRent= rs.getInt("maxid");
                        System.out.println("max id ne: " + maxIDRent);
                    }else{
                        System.out.println("khong tim ra " );
                    }    
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.toString(),"NULL",JOptionPane.ERROR_MESSAGE);
                }
        a.Query("UPDATE RentalTransaction SET TOTALPRICE ='" + total + "', STATUSRETURN = '0' WHERE IDRent= '" + maxIDRent + "'");     
        String message = "ID Rent: " + maxIDRent +"\nDay Rent:"+currentDate+ "\nDay Return: "+selectedLocalDate+"\nTotal Price: " + total ;
        JOptionPane.showMessageDialog(null, message, "Transaction Details", JOptionPane.INFORMATION_MESSAGE);  
        String id= txtIdCus.getText();
        a.Query("UPDATE Customers SET STATUSRENT = '1' WHERE ID = '" + id + "'");
        clearFieldsCus();
        clearVideoFieldVid();
        ClearAfterPay();
        ClearJTable();
        }else{
            String message = "Not enough money" ;
            JOptionPane.showMessageDialog(null, message, "Transaction Details", JOptionPane.INFORMATION_MESSAGE); 
        }
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void txtIdCusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCusKeyReleased
        // TODO add your handling code here:
        searchCus();
        
    }//GEN-LAST:event_txtIdCusKeyReleased

    private void txtIdCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCusActionPerformed

    private void txtIdVidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdVidKeyReleased
        // TODO add your handling code here:
        searchVid();
    }//GEN-LAST:event_txtIdVidKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
       addList();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtCusPayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusPayKeyReleased
        // TODO add your handling code here:
        int cuspay= Integer.parseInt(txtCusPay.getText()) ;
        int total=Integer.parseInt(txtTotalPrice.getText());
        int exchange= cuspay - total;
        txtExchange.setText(String.valueOf(exchange));
        
    }//GEN-LAST:event_txtCusPayKeyReleased

    private void searchCus(){
        String idCus = txtIdCus.getText();
        if (idCus.isEmpty()) {
            clearFieldsCus();  
            return;
        }
        DBAccess acc = new DBAccess();
        ResultSet rs = acc.Query("SELECT * FROM Customers WHERE ID =  '" + idCus + "'");
        
        
        try {
            if (rs.next()) {
                String name = rs.getString("Name");
                String Dob = rs.getString("DOB");
                String Phone= rs.getString("PHONE");
                String Addr= rs.getString("ADDRESS");
                int SRent= rs.getInt("STATUSRENT");
                int Active= rs.getInt("iSACTIVE");
                if (SRent == 0){
                    txtStatus.setText("Not Rented");
                }else{
                    txtStatus.setText("Rented");
                }
                
                if (Active == 0){
                    txtActive.setText("Inactive");
                }else{
                    txtActive.setText("Active");
                }
                txtNameCus.setText(name);
                txtPhone.setText(Phone);
                txtDOB.setText(Dob);
                txtAddr.setText(Addr);
            } else {
                txtNameCus.setText("No data found");
                txtPhone.setText(null);
                txtDOB.setText(null);
                txtAddr.setText(null);
                txtActive.setText(null);
                txtStatus.setText(null); 
            }
        } catch (SQLException ex) {
            // Handle any SQL exception
            JOptionPane.showMessageDialog(null, ex.toString(),"NULL",JOptionPane.ERROR_MESSAGE);
        
        }
    }
    private void clearFieldsCus() {
    txtNameCus.setText("");
    txtPhone.setText("");
    txtDOB.setText("");
    txtAddr.setText("");
    txtActive.setText("");
    txtStatus.setText("");
}
    private void searchVid(){
        String idVid = txtIdVid.getText();
        if (idVid.isEmpty()) {
            clearVideoFieldVid();  
            return;
        }
        DBAccess acc = new DBAccess();
        ResultSet rs = acc.Query("SELECT * FROM Video WHERE ID =  '" + idVid + "'");
        
        
        try {
            if (rs.next()) {
                String name = rs.getString("Name");
                String type = rs.getString("TYPE");
                String Author= rs.getString("AUTHOR");
                String Release= rs.getString("YEAROFRELEASE");
                int amount= rs.getInt("AMOUNT");
                int Price= rs.getInt("PRICEOFDAY");
               
                txtNameVid.setText(name);
                txtType.setText(type);
                txtAu.setText(Author);
                txtAmount.setText(Integer.toString(amount));
                txtPrice.setText(Integer.toString(Price));
            } else {
                txtNameVid.setText("No data found");
                txtType.setText(null);
                txtAu.setText(null);
                txtAmount.setText(null);
                txtPrice.setText(null);
            }
        } catch (SQLException ex) {
            // Handle any SQL exception
            JOptionPane.showMessageDialog(null, ex.toString(),"NULL",JOptionPane.ERROR_MESSAGE);
        
        }
    }
    private void clearVideoFieldVid() {
    txtNameVid.setText("");
    txtType.setText("");
    txtAu.setText("");
    txtAmount.setText("");
    txtPrice.setText("");
    
}
    private void updateDateTime() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd  HH:mm:ss");
//        DateTimeFormatter format= DateTimeFormatter.ofPattern("yyyy-MM-dd ");
//        String dateBr = currentDate.format(format);
        String formattedDateTime = dateFormat.format(new Date());
        labelDate.setText(formattedDateTime);
//        labelTime.setText(dateBr);
        
    }
    public boolean checkRentedCus(){
        String idCus = txtIdCus.getText();
        DBAccess acc = new DBAccess();
        ResultSet rs = acc.Query("SELECT STATUSRENT FROM Customers WHERE ID =  '" + idCus + "'");
        try {
            if (rs.next()) {
                
                int Active= rs.getInt("STATUSRENT");
                if (Active == 0){
                    return false;
                }else{
                    return true;
                }               
            } else {
            }
        } catch (SQLException ex) {
            // Handle any SQL exception
            JOptionPane.showMessageDialog(null, ex.toString(),"NULL",JOptionPane.ERROR_MESSAGE);
        
        }
        return true;
      
    }
    private void addList(){  
        if(checkRentedCus() == false){
            DBAccess a= new DBAccess();
            Date selectedDate = selectDay.getDate();
            String idCus= txtIdCus.getText();
            String idVid=txtIdVid.getText();
            int price=0;
            int priceOfVid=0;
            int amountVid= Integer.parseInt(txtQuantity.getText());
            int amountStore=Integer.parseInt(txtAmount.getText());
            int maxIDRent=0;           
                if (selectedDate != null) {
                    LocalDate selectedLocalDate = selectedDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();             
                    LocalDate currentDate = LocalDate.now();                 
                    long daysDifference = java.time.temporal.ChronoUnit.DAYS.between(currentDate, selectedLocalDate);
                    if(checkTransaction==0){
                        a.Query("Insert into RentalTransaction(DateOfBorrow,DateOfReturn,ID)"+
                            "values('"+currentDate+"','"+selectedLocalDate+"','"+idCus+"')");
                        checkTransaction++;
                        System.out.println("check coi co qua đơn mới k nè"+checkTransaction);
                    };
                    ResultSet rs = a.Query("SELECT MAX(IDRent)AS maxid FROM RentalTransaction");
                    try {
                        if(rs.next()){
                            maxIDRent= rs.getInt("maxid");
                            System.out.println("max id ne: " + maxIDRent);
                        }else{
                            System.out.println("khong tim ra " );
                        }    
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.toString(),"NULL",JOptionPane.ERROR_MESSAGE);
                    }
                    ResultSet rs1 = a.Query("SELECT PRICeOFDAY FROM VIDEO WHERE ID= "+idVid);
                    try {
                        if(rs1.next() && amountVid <= amountStore){
                            price= rs1.getInt("PRICEOFDAY");
                            System.out.println("Gia tien ne" + price);
                            priceOfVid=(int) (amountVid*price*daysDifference);
                            System.out.println("Gia tien ne" + priceOfVid);
                            Total= Total + priceOfVid;
                            txtTotalPrice.setText(String.valueOf(Total));
                        }else{
                            System.out.println("khong tim ra gia " );
                        }    
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.toString(),"NULL",JOptionPane.ERROR_MESSAGE);
                    };        
                    if(amountVid <= amountStore){
                        a.Query("Insert into DetailTransaction(IDRent,IDVid,Amount,RentalFee)"+
                            "values('"+maxIDRent+"','"+idVid+"','"+amountVid+"','"+priceOfVid+"')");
                        a.Query("UPDATE Video SET Amount = Amount -"+amountVid+" WHERE ID ="+ idVid);  
                        DefaultTableModel jtb = (DefaultTableModel)jTable1.getModel();
                        Object fillTable[]={txtNameVid.getText(),amountVid,daysDifference,priceOfVid};
                        jtb.addRow(fillTable);
                    }else{
                        JOptionPane.showMessageDialog(null, "Over Quantity");
                    }
                } else {
                        JOptionPane.showMessageDialog(null, "Vui lòng chọn một ngày.");
                }
        }else{
            JOptionPane.showMessageDialog(null, "Rented");
        }
        
    }
    public void ClearAfterPay(){
        txtIdCus.setText(null);
        txtIdVid.setText(null);
        txtQuantity.setText(null);
        selectDay.setDate(null);
        txtCusPay.setText(null);
        txtTotalPrice.setText(null);
        txtExchange.setText(null);
    }
    public void ClearJTable(){
        DefaultTableModel jtb = (DefaultTableModel)jTable1.getModel();
        jtb.setRowCount(0); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentVideo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelTime;
    private com.toedter.calendar.JDateChooser selectDay;
    private javax.swing.JTextField txtActive;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAu;
    private javax.swing.JLabel txtAuthor;
    private javax.swing.JTextField txtCusPay;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JLabel txtExchange;
    private javax.swing.JTextField txtIdCus;
    private javax.swing.JTextField txtIdVid;
    private javax.swing.JTextField txtNameCus;
    private javax.swing.JTextField txtNameVid;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JLabel txtPriceRent;
    private javax.swing.JLabel txtPriceRent1;
    private javax.swing.JLabel txtPriceRent2;
    private javax.swing.JLabel txtPriceRent3;
    private javax.swing.JLabel txtPriceRent4;
    private javax.swing.JLabel txtPriceRent5;
    private javax.swing.JLabel txtPriceRent6;
    private javax.swing.JLabel txtPriceRent7;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JLabel txtTotalPrice;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
